markdown: redcarpet
destination : /home/john/github/generated
encoding: UTF-8
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
